#ifndef HEAD_TEST
#define HEAD_TEST

#define MACHINE_IP "192.168.0.179"
#define MULTICAST_PORT 50002
#define MULTICAST_IP "235.0.0.1"
#define MACHINE_PORT MULTICAST_PORT
#define SHARED_BUFFER_SIZE (10 * MAX_FRAME_SIZE)

#define SHARED_KEY "buf"

#endif